In [2]:
import numpy as np
import pandas as pd

In [4]:
name = "james"
name

'james'

In [7]:
fruits = ["banana", "orange", "mango"]
fruits


['banana', 'orange', 'mango']

In [10]:
fruits = np.array(fruits)

In [11]:
fruits

array(['banana', 'orange', 'mango'], dtype='<U6')

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
random_values = np.ones(5)

In [19]:
np.linspace(1, 10, 9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [20]:
students = [["Sampson","6ft 1'", "Dark"],["Blessing","6ft 1'", "Dark"],["Eleanor","6ft 1'", "Fair"],["Dare","6ft 1'", "Dark"]]
students


[['Sampson', "6ft 1'", 'Dark'],
 ['Blessing', "6ft 1'", 'Dark'],
 ['Eleanor', "6ft 1'", 'Fair'],
 ['Dare', "6ft 1'", 'Dark']]

In [21]:
np.array(students)

array([['Sampson', "6ft 1'", 'Dark'],
       ['Blessing', "6ft 1'", 'Dark'],
       ['Eleanor', "6ft 1'", 'Fair'],
       ['Dare', "6ft 1'", 'Dark']], dtype='<U8')

In [23]:
np.linspace(1, 10, 9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
random_num = np.random.rand(2,5)
random_num

array([[0.88924444, 0.53933601, 0.97970376, 0.39682709, 0.40666268],
       [0.8962666 , 0.4462342 , 0.37949981, 0.92704962, 0.45401187]])

In [36]:
random_num[1,4]

0.30519956631548817

In [40]:
random_num = np.random.randn(2,5)
random_num * 100

array([[ -43.37002879, -183.57114409,  -66.92803626,   22.32598522,
          68.71163547],
       [ 209.11624852,  106.83518651,   75.91585231, -176.723488  ,
          16.96324064]])

In [44]:
columns = ["name", "height", "complexion"]

In [45]:
df = pd.DataFrame(students, columns=columns)
df

name  height complexion
0   Sampson  6ft 1'       Dark
1  Blessing  6ft 1'       Dark
2   Eleanor  6ft 1'       Fair
3      Dare  6ft 1'       Dark

In [48]:
df = pd.read_csv(r"C:\Users\USER\Downloads\Housing.csv\Housing.csv")

In [54]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7229300521  20141013T000000  231300.0         2       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [56]:
df["price"]

0        231300.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64